import { useMemo, useState } from "react";
import { AlertTriangle, ArrowUpRight, BookOpen, Bot, CheckCircle2, CircleHelp, RotateCcw, Send, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import type { ChatResponse } from "../../../shared/support";

type Message = { role: "user" | "assistant"; content: string; response?: ChatResponse };
const suggestions = ["How do I download an invoice?", "I can’t log in to my workspace", "Where can I check webhook retries?"];

export default function Home() {
  const [conversationId, setConversationId] = useState<string>();
  const [draft, setDraft] = useState("");
  const [messages, setMessages] = useState<Message[]>([]);
  const [error, setError] = useState("");
  const chat = trpc.support.chat.useMutation({ onSuccess: (data) => { setConversationId(data.conversationId); setMessages(current => [...current, { role: "assistant", content: data.answer, response: data }]); setDraft(""); setError(""); }, onError: (err) => setError(err.message || "Something went wrong while contacting SupportPilot.") });
  const reset = trpc.support.reset.useMutation({ onSuccess: () => { setConversationId(undefined); setMessages([]); setError(""); } });
  const canSend = draft.trim().length > 0 && !chat.isPending;
  const stats = useMemo(() => ({ answered: messages.filter(m => m.response && !m.response.escalated).length, escalated: messages.filter(m => m.response?.escalated).length }), [messages]);
  const send = (text = draft) => { if (!text.trim() || chat.isPending) return; setMessages(current => [...current, { role: "user", content: text.trim() }]); chat.mutate({ message: text.trim(), conversationId }); };

  return <main className="app-shell">
    <header className="topbar"><div className="brand"><div className="brand-mark"><Sparkles size={18} /></div><div><div className="brand-name">SupportPilot</div><div className="brand-sub">Tier-1 support intelligence</div></div></div><div className="topbar-actions"><span className="status-dot"><span /> Knowledge base online</span><Button variant="outline" className="reset-btn" onClick={() => conversationId && reset.mutate({ conversationId })} disabled={!conversationId || reset.isPending}><RotateCcw size={15} /> New conversation</Button></div></header>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><ShieldCheck size={15} /> Grounded by design</div><h1>Support that knows<br /><em>when to pause.</em></h1><p>Ask a Tier-1 question and get a clear, source-backed answer. When the evidence is not enough, SupportPilot makes the handoff visible.</p><div className="hero-metrics"><div><strong>{stats.answered}</strong><span>resolved safely</span></div><div><strong>{stats.escalated}</strong><span>escalated for review</span></div><div><strong>24</strong><span>knowledge sources</span></div></div></div><div className="hero-orbit"><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><div className="hero-core"><Bot size={35} /><span>AI<br />EMPLOYEE</span></div><div className="orbit-label label-top">CLASSIFY</div><div className="orbit-label label-right">RETRIEVE</div><div className="orbit-label label-bottom">ESCALATE</div></div></section>
    <section className="workspace"><aside className="sidebar"><div className="side-heading"><span>Playground</span><span className="live-pill">LIVE</span></div><div className="side-card"><div className="side-card-icon"><CircleHelp size={17} /></div><div><strong>Try a support question</strong><p>Responses are limited to the synthetic SupportPilot FAQ.</p></div></div><div className="side-section"><div className="side-label">Suggested prompts</div>{suggestions.map(prompt => <button className="suggestion" key={prompt} onClick={() => send(prompt)}><span>{prompt}</span><ArrowUpRight size={14} /></button>)}</div><div className="side-section protocol"><div className="side-label">Safety protocol</div><div className="protocol-item"><CheckCircle2 size={15} /> Evidence before answers</div><div className="protocol-item"><CheckCircle2 size={15} /> No irreversible actions</div><div className="protocol-item"><CheckCircle2 size={15} /> Human handoff when unsure</div></div><div className="side-footer">DEMO ENVIRONMENT<br /><span>Fictional workspace · no live data</span></div></aside>
      <div className="chat-panel"><div className="chat-header"><div><span className="panel-kicker">CONVERSATION</span><h2>Support desk</h2></div><div className="conversation-state"><span className="pulse" /> {conversationId ? "Session active" : "Ready when you are"}</div></div><div className="messages" aria-live="polite">{messages.length === 0 && <div className="empty-state"><div className="empty-icon"><Bot size={26} /></div><h3>How can we help?</h3><p>Start with a billing, technical, or account access question. I’ll show my reasoning, evidence, and confidence.</p><div className="empty-rule" /></div>}{messages.map((message, index) => <div className={`message-row ${message.role}`} key={`${message.content}-${index}`}><div className="avatar">{message.role === "user" ? <UserRound size={16} /> : <Bot size={17} />}</div><div className="message-content"><div className="message-meta">{message.role === "user" ? "You" : "SupportPilot"}<span>{message.role === "assistant" && message.response ? new Date(message.response.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : ""}</span></div><div className="bubble">{message.content}</div>{message.response && <ResponseDetails data={message.response} />}</div></div>)}{chat.isPending && <div className="message-row assistant"><div className="avatar"><Bot size={17} /></div><div className="message-content"><div className="message-meta">SupportPilot</div><div className="bubble typing"><span /><span /><span /></div></div></div>}{error && <div className="error-banner"><AlertTriangle size={17} /><span>{error}</span></div>}</div><div className="composer"><Textarea value={draft} onChange={e => setDraft(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(); } }} placeholder="Describe your support question…" aria-label="Support question" /><Button className="send-btn" onClick={() => send()} disabled={!canSend}><Send size={17} /> Send</Button><div className="composer-note">Press Enter to send · Shift + Enter for a new line</div></div></div></section>
    <footer className="site-footer"><span>SUPPORTPILOT / TIER-1 AI EMPLOYEE</span><span>Answers are grounded in synthetic knowledge-base content.</span></footer>
  </main>;
}

function ResponseDetails({ data }: { data: ChatResponse }) { return <div className="response-details"><div className="detail-line"><span className={`category-badge ${data.classification.category.toLowerCase().split(" ")[0]}`}>{data.classification.category}</span><span className="confidence"><span className="confidence-bar"><i style={{ width: `${data.classification.confidence * 100}%` }} /></span>{Math.round(data.classification.confidence * 100)}% confidence</span></div><div className="reason">{data.classification.reason}</div>{data.escalated ? <div className="escalation"><div className="escalation-title"><AlertTriangle size={16} /> Human review recommended</div><div>{data.escalationReasonMessage}</div><small>Reason code: {data.escalationReasonCode}</small></div> : <div className="citations"><div className="citation-label"><BookOpen size={14} /> Evidence used</div>{data.citations.map(source => <div className="citation" key={source.sourceId}><span>{source.sourceId}</span><small>{Math.round(source.score * 100)}% match · {source.title}</small></div>)}</div>}</div> }
